import { SubjectCategory } from '@/types'

export const SUBJECT_CATEGORIES: SubjectCategory[] = [
  {
    id: 'femme',
    label: 'La Femme',
    emoji: '🌸',
    subjects: [
      'La femme est la fleur de la terre',
      'La femme trouve suffisamment sa place dans la société moderne',
      'L\'égalité des sexes est une réalité, pas un mythe',
      'La représentation de la femme dans les médias est stéréotypée',
      'La femme congolaise face aux défis de la modernité',
      'La femme et l\'éducation : deux réalités inséparables',
      'La place de la femme dans la politique congolaise',
      'La maternité est-elle un obstacle à l\'épanouissement de la femme ?',
      'La femme africaine : entre tradition et modernité',
      'La violence faite aux femmes : un fléau qu\'il faut éradiquer',
      'La femme est le pilier de la famille',
      'L\'émancipation de la femme profite à toute la société',
      'La femme dans le monde du travail en RDC',
      'Le mariage précoce : un obstacle au développement de la femme',
      'La femme entrepreneuriale en Afrique centrale',
      'La scolarisation des filles : un impératif pour le développement',
      'La femme et la religion en Afrique noire',
      'La femme chef d\'entreprise : mythe ou réalité en RDC ?',
      'Le harcèlement sexuel au travail : une réalité que la femme subit',
      'La femme dans la littérature africaine : objet ou sujet ?',
    ],
  },
  {
    id: 'travail',
    label: 'Le Travail',
    emoji: '💼',
    subjects: [
      'Le travail est source d\'épanouissement pour l\'homme',
      'Le chômage : un véritable fléau pour la jeunesse congolaise',
      'Le travail informel en RDC : frein ou moteur du développement ?',
      'La technologie menace-t-elle l\'emploi en Afrique ?',
      'Le droit au travail est un droit fondamental de l\'être humain',
      'L\'entrepreneuriat : une solution au chômage des jeunes en RDC',
      'Le travail des enfants : une réalité alarmante en RDC',
      'La formation professionnelle, clé du développement économique',
      'Le télétravail : révolution ou régression du monde professionnel ?',
      'Le travail de la terre : un secteur à valoriser en RDC',
      'La grève : un droit ou un obstacle à la productivité ?',
      'L\'exode rural en RDC : causes et conséquences sur le monde du travail',
      'Le travail bénévole : un acte de civisme ou une exploitation ?',
      'La retraite est-elle une récompense méritée ?',
      'L\'artisanat congolais : un secteur à valoriser',
      'La robotisation va-t-elle transformer le marché du travail africain ?',
      'Le travail est-il une nécessité ou une passion ?',
      'La corruption dans l\'administration : un obstacle au travail méritoire',
      'Les mines en RDC : richesse naturelle, pauvreté humaine',
      'L\'agriculture en RDC : vocation naturelle ou secteur négligé ?',
    ],
  },
  {
    id: 'science',
    label: 'La Science',
    emoji: '🔬',
    subjects: [
      'L\'informatique : science bénéfique ou dangereuse ?',
      'Les conséquences de l\'IA sur l\'emploi en Afrique',
      'L\'effet des réseaux sociaux sur la santé mentale des jeunes',
      'La technologie peut-elle remplacer l\'enseignant ?',
      'La téléphonie mobile : progrès ou régression sociale ?',
      'La science est-elle la solution à tous les problèmes de l\'humanité ?',
      'Le changement climatique : la science face à l\'urgence planétaire',
      'Les médicaments traditionnels africains face à la médecine moderne',
      'La déforestation en RDC : un désastre écologique annoncé',
      'L\'accès à l\'eau potable : un défi scientifique et humanitaire',
      'La recherche scientifique en Afrique : état des lieux et perspectives',
      'Internet : fenêtre sur le monde ou piège pour les jeunes ?',
      'L\'énergie solaire : une solution pour l\'électrification rurale en RDC',
      'Les OGM : progrès scientifique ou danger pour l\'alimentation ?',
      'La médecine moderne a-t-elle rendu la médecine traditionnelle inutile ?',
      'Le nucléaire : énergie d\'avenir ou menace existentielle ?',
      'L\'espace : l\'Afrique a-t-elle sa place dans la conquête spatiale ?',
      'Les maladies tropicales en RDC : défis et solutions scientifiques',
      'La blockchain : révolution technologique ou effet de mode ?',
      'L\'ordinateur a-t-il rendu l\'homme plus intelligent ou plus paresseux ?',
    ],
  },
  {
    id: 'education',
    label: 'L\'Éducation',
    emoji: '📚',
    subjects: [
      'L\'éducation est la clé du développement d\'un pays',
      'L\'école congolaise face aux défis du XXIe siècle',
      'La gratuité de l\'enseignement en RDC : bilan et perspectives',
      'La discipline à l\'école : nécessité ou violence ?',
      'L\'éducation des parents est aussi importante que celle des enfants',
      'Les examens scolaires mesurent-ils réellement les compétences ?',
      'La bibliothèque scolaire : un outil indispensable trop souvent négligé',
      'L\'éducation religieuse a-t-elle sa place dans les écoles publiques ?',
      'Le sport scolaire : un complément indispensable à l\'éducation intellectuelle',
      'La sévérité du professeur est-elle une vertu pédagogique ?',
      'L\'éducation sexuelle à l\'école : tabou ou nécessité ?',
      'Le numérique dans les salles de classe congolaises : utopie ou réalité ?',
      'Les devoirs à la maison : une aide ou un fardeau pour les élèves ?',
      'L\'enseignement privé contre l\'enseignement public en RDC',
      'La langue d\'enseignement en Afrique : entre langues nationales et langues étrangères',
      'L\'abandon scolaire en RDC : causes et solutions',
      'L\'enseignement technique et professionnel : parent pauvre de l\'éducation congolaise',
      'Le rôle de la famille dans l\'éducation de l\'enfant',
      'Peut-on réformer le système éducatif congolais ?',
      'L\'élève congolais face aux nouvelles technologies éducatives',
    ],
  },
  {
    id: 'culture',
    label: 'Culture générale',
    emoji: '🌍',
    subjects: [
      'La paix est-elle possible en République Démocratique du Congo ?',
      'La démocratie est-elle adaptée à l\'Afrique ?',
      'La mondialisation est-elle une chance ou une menace pour l\'Afrique ?',
      'La corruption : principal obstacle au développement de la RDC',
      'L\'identité culturelle africaine face à l\'occidentalisation',
      'La liberté de presse est-elle une réalité en RDC ?',
      'La migration africaine vers l\'Europe : fuite ou aspiration légitime ?',
      'La pauvreté en RDC : conséquence de l\'ignorance ou du mauvais gouvernement ?',
      'Le patriotisme : vertu ou illusion dans l\'Afrique contemporaine ?',
      'La peine de mort doit-elle être abolie ?',
      'L\'Afrique peut-elle se développer sans l\'aide extérieure ?',
      'Les droits de l\'homme sont-ils vraiment universels ?',
      'La religion est-elle un frein ou un moteur du développement ?',
      'L\'unité africaine : rêve ou réalité ?',
      'Le tribalisme : cancer de la société congolaise',
      'La jeunesse africaine : désenchantée ou porteuse d\'espoir ?',
      'La langue française en Afrique : atout ou vestige du colonialisme ?',
      'La presse et l\'opinion publique en RDC',
      'Le sport comme vecteur de développement national',
      'L\'Afrique subsaharienne face aux enjeux du développement durable',
    ],
  },
]

export function getSubjectCategory(id: string): SubjectCategory | undefined {
  return SUBJECT_CATEGORIES.find((c) => c.id === id)
}
